---
- hosts: all
  remote_user: root
  become_user: root
  become: true
  become_method: sudo
  tasks:
   - name: falcon
     lineinfile: dest="/etc/rc.local" insertbefore="exit 0" line="su - /data/ops/updater/falcon-agent-private/5.1.2/control restart"