---
- name: set-jdk
  remote_user: root
  become: true
  become_method: sudo
 
  - name: Install Java 1.7
    copy: src=/data/jdk-7u80-linux-x64.tar.gz dest=/tmp mode=0744

  - name: Extract archive
    command: chdir=/tmp /bin/tar -xzf jdk-7u80-linux-x64.tar.gz -C /usr/local

  - name: java
    lineinfile: dest=/etc/profile regexp="^JAVA_HOME=" line="JAVA_HOME=/usr/local/jdk1.7.0_80"

  - name: jre
    lineinfile: dest=/etc/profile regexp="^JRE_HOME=" line="JRE_HOME=/usr/local/jdk1.7.0_80/jre"

  - name: class_path
    lineinfile: dest=/etc/profile regexp="^CLASS_PATH=" line="CLASS_PATH=.:$JAVA_HOME/lib/jt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib"

  - name : path
    lineinfile: dest=/etc/profile regexp="^PATH=\$PATH:\$JAVA_HOME" line="PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin"

  - name: export
    lineinfile : dest=/etc/profile regexp="^export JAVA_HOME" line="export JAVA_HOME JRE_HOME PATH CLASSPATH"

  - name: source profile
    shell: ". /etc/profile"