CREATE TABLE `record_version` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `school` varchar(255) DEFAULT NULL,
  `appCode` varchar(255) DEFAULT NULL,
  `sqlfile` varchar(5000) DEFAULT NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;